version: '3'

services:
  hub:
    image: selenium/hub:3.141.59
    ports:
      - "4444:4444"
    restart: always

  chrome:
    image: selenium/node-chrome:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    restart: always

  firefox:
    image: selenium/node-firefox:3.141.59
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    restart: always

  pytest:
    build:
      context: ./
    image: azurecin/automation-test:0.1
    container_name: pytest
    volumes:
      - ./reports:/automation-test/reports/
      - ./screenshots:/automation-test/screenshots/
    tty: true
    depends_on:
      - chrome
      - firefox