version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:jessie-node-browsers
        auth:
          username: azurecin
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - run: mkdir reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest --html=./reports/report.html tests/ --capture=tee-sys --publish
      - store_artifacts:
          path: reports
          destination: reports
          when: always
