version: 2.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8.11-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create dir reports
          command: mkdir reports
      - run:
          name: Create dir screenshots
          command: mkdir screenshots
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest --html=./reports/report.html --capture=tee-sys
      - store_artifacts:
          path: screenshots
          destination: screenshots
      - store_artifacts:
          path: reports
          destination: reports
workflows:
    do_not_build:
      when:
        and:
          - not:
              equal: [ develop, << pipeline.git.branch >> ]
      jobs:
          - test
    build:
        when:
          and:
            - equal: [ develop, << pipeline.git.branch >> ]
        jobs:
            - test