version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.11-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create Report dir
          command: mkdir reports
      - run:
          name: Create Screenshots dir
          command: mkdir screenshots
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install VNP packages
          command: |
            apt-get update
            apt-get install strongswan xl2tpd net-tools
      - run:
          name: Configure strongSwan
          command: |
            cat > /etc/ipsec.conf <<EOF

            conn myvpn
              auto=add
              keyexchange=ikev1
              authby=secret
              type=transport
              left=%defaultroute
              leftprotoport=17/1701
              rightprotoport=17/1701
              right=$VPN_SERVER_IP
              ike=aes128-sha1-modp2048
              esp=aes128-sha1
            EOF

            cat > /etc/ipsec.secrets <<EOF
            : PSK "$VPN_IPSEC_PSK"
            EOF
      - run:
          name: Configure xl2tpd
          command: |
            cat > /etc/xl2tpd/xl2tpd.conf <<EOF
            [lac myvpn]
            lns = $VPN_SERVER_IP
            ppp debug = yes
            pppoptfile = /etc/ppp/options.l2tpd.client
            length bit = yes
            EOF

            cat > /etc/ppp/options.l2tpd.client <<EOF
            ipcp-accept-local
            ipcp-accept-remote
            refuse-eap
            require-chap
            noccp
            noauth
            mtu 1280
            mru 1280
            noipdefault
            defaultroute
            usepeerdns
            connect-delay 5000
            name "$VPN_USER"
            password "$VPN_PASSWORD"
            EOF

            chmod 600 /etc/ppp/options.l2tpd.client
      - run:
          name: Create xl2tpd control file
          command: |
            mkdir -p /var/run/xl2tpd
            touch /var/run/xl2tpd/l2tp-control
      - run:
          name: Restart services
          command: |
            service strongswan restart
            service xl2tpd restart
      - run:
          name: Start the IPsec connection
          command: |
            ipsec up myvpn
      - run:
          name: Start the L2TP connection
          command: |
            echo "c myvpn" > /var/run/xl2tpd/l2tp-control
      - run:
          name: Check existing default route
          command: |
            ip route
            default_gw_IP=$(ip route | grep default | awk '{ print $3 }')
      - run:
          name: Exclude VPN server's IP from the new default route
          command: |
            route add YOUR_VPN_SERVER_IP gw $default_gw_IP
      - run:
          name: Add a new default route
          command: |
            route add default dev ppp0
      - run:
          name: Verify that your traffic
          command: |
            wget -qO- http://ipv4.icanhazip.com; echo

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest --html=./reports/report.html tests/ --capture=tee-sys --publish
      - store_artifacts:
          path: screenshots
          destination: screenshots
      - store_artifacts:
          path: reports
          destination: reports
