version: 2.1
jobs:
  build and test:
    docker:
      - image: circleci/python:3.8.11-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create dir
          command: mkdir reports screenshots
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python3 -m pytest --html=./reports/report.html tests/ --capture=tee-sys
      - run:
          name: Package up screenshots
          command: |
            pushd screenshots
            zip -r ~/screenshots.zip *
            popd
      - store_artifacts:
          path: ~/screenshots.zip
          destination: screenshots.zip
      - store_artifacts:
          path: screenshots
          destination: screenshots
      - store_artifacts:
          path: reports
          destination: reports
